//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class UnloadJob : IJob
{
	enum Modes
	{
		Start, Go,Pick,Unload,End
	}

	Modes state = Modes.Start;
	IInventory inventory;
	Vector3 buildingPos;

	public UnloadJob()
	{
	}

	public UnloadJob(JobManager jobManager, ICustomer customer,Vector3 target, IInventory targetInventory) 
		: base(jobManager, customer)
	{
		inventory = targetInventory;
		buildingPos = target;
	}

	#region implemented abstract members of IJob

	public override void OnDriven ()
	{
		if(inventory.Quantity>0)
		{
			Pile p = inventory.FirstPile;
			worker.Pick(inventory,new PileRequest(p,inventory.Quantity));
			state = Modes.Unload;
			worker.Unload();		
		}
		else
		{
			state=Modes.End;
			Complete();
		}

	}

	public override void OnLoaded ()
	{

	}

	public override void OnUnloaded ()
	{
		state=Modes.End;
		Complete();
	}

	public override void UpdateJob ()
	{
		switch(state)
		{
		case Modes.Start:
			Item[] items = inventory.GetItemTypes();
			if(jobManager.M.FindInventoryFor(items[0])==null)
			{
				DelayThisJob();
				state = Modes.Start;
			}
			else
			{
				worker.DriveTo(buildingPos, inventory.collider);
				state = Modes.Go;
			}
			break;
		}
	}

	#endregion

	public override void Save (WriterEx b)
	{
		base.Save (b);
		b.WriteEnum(state);
		b.Write(buildingPos);
		b.WriteLink(inventory);
	}
	
	public override void Load (Manager m, ReaderEx r)
	{
		base.Load (m, r);
		state = (Modes)r.ReadEnum(typeof(Modes));
		buildingPos = r.ReadVector3();
		inventory = (IInventory)r.ReadLink(m);
	}
}


