//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18063
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public struct IntVector3
{
	int x,y,z;
	public int X{get{return x;}}
	public int Y{get{return y;}}
	public int Z{get{return z;}}



	public IntVector3 (int _x,int _y,int _z)
	{
		x=_x;
		y=_y;
		z=_z;
	}

	public int Sum()
	{
		return x+y+z;
	}

	public static IntVector3 operator+(IntVector3 v1, IntVector3 v2)
	{
		return new IntVector3(v1.x+v2.x,v1.y+v2.y,v1.z+v2.z);
	}

	public static Vector3 operator*(IntVector3 v, float k)
	{
		return new Vector3(v.x*k,v.y*k,v.z*k);
	}

	public static Vector3 operator/(IntVector3 v, float k)
	{
		return new Vector3(v.x/k,v.y/k,v.z/k);
	}

	public static IntVector3 operator-(IntVector3 v1, IntVector3 v2)
	{
		return new IntVector3(v1.x-v2.x,v1.y-v2.y,v1.z-v2.z);
	}

	public static IntVector3 operator*(IntVector3 v, int k)
	{
		return new IntVector3(v.x*k,v.y*k,v.z*k);
	}

	public static bool operator==(IntVector3 v1, IntVector3 v2)
	{
		return v1.x==v2.x && v1.y==v2.y && v1.z==v2.z;
	}

	public static bool operator!=(IntVector3 v1, IntVector3 v2)
	{
		return v1.x!=v2.x || v1.y!=v2.y || v1.z!=v2.z;
	}
}


