//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.IO;
using System;

public class ReaderEx : BinaryReader
{
	public ReaderEx(Stream stream) : base(stream)
	{

	}

	public object ReadEnum(Type enumType)
	{
		return Enum.Parse (enumType,ReadString());
	}

}


