//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

public class UidContainer : IStorable
{
	private static int nextUid=0;
	private int uid;
	private object owner;
	public int UID{
		get{
			return uid;
		}
	}

	public UidContainer (object owner)
	{
		uid = nextUid++;
		this.owner=owner;
	}

	#region IStorable implementation
	// do not call this
	public void SaveUid(WriterEx b)
	{
		throw new UnityException("You should call Save() to store uid. There is a bug in code.");
	}

	// do not call this
	public void LoadUid(Manager m, ReaderEx r)
	{
		throw new UnityException("You should call Load() to load uid. There is a bug in code.");
	}

	//call this to save this uid
	public void Save (WriterEx b)
	{
		b.Write(UID);
	}

	//call this to load uid and add a record to LoadedLinks
	public void Load (Manager m, ReaderEx r)
	{
		int loadeduid = r.ReadInt32();
		m.LoadedLinks.Add(loadeduid, owner);
	}

	public int GetUID()
	{
		return uid;
	}
	#endregion
}


