//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.IO;
using System;
using UnityEngine;

public class WriterEx : BinaryWriter
{
	public static readonly Int32 MAGIC = 0xc7f042;

	public void WriteMagic()
	{
		Write(MAGIC);
	}

	public WriterEx(Stream stream) : base(stream)
	{
		
	}

	// val can be null, in that case empty string is written
	public void WriteEx(Block val)
	{
		if(val!=null)
			Write (val.Name);
		else 
			Write ("");
	}

	public void WriteEx(Item val)
	{
		if(val!=null)
			Write (val.Name);
		else 
			Write ("");
	}

	public void WriteEx(Vehicle val)
	{

		if(val!=null)
		{
			Debug.Log("Storing vehicle "+val.Name);
			Write (val.Name);
		}
		else 
		{
			Debug.Log("Storing vehicle with null pointer");
			Write ("");
		}
	}

	public void WriteEx(Recipe val)
	{
		if(val!=null)
			Write (val.Name);
		else 
			Write ("");
	}

	public void WriteEx(Building val)
	{
		if(val!=null)
			Write (val.Name);
		else 
			Write ("");
	}

	public void WriteEnum(object obj)
	{
		Write (Enum.GetName(obj.GetType(),obj));
	}

	public void Write(Color color)
	{
		Write((double)color.r);
		Write((double)color.g);
		Write((double)color.b);
		Write((double)color.a);
	}
	public void Write(Vector3 vec)
	{
		Write((double)vec.x);
		Write((double)vec.y);
		Write((double)vec.z);

	}

	public void WriteLink(IStorable obj)
	{
		if(obj==null)
			Write (0);
		else 
			Write (obj.GetUID());
	}


}



